import 'package:app/main.directories.g.dart';
import 'package:app/theme/tokens.dart';
import 'package:flutter/material.dart';
import 'package:widgetbook/widgetbook.dart';

void main() {
  runApp(const WidgetbookApp());
}

/// Widgetbook catalog for the Button / Input / Card components implemented
/// from docs/design-system-rules.md + docs/figma-fixtures (Flutter track of
/// the Figma-to-code comparison research). Component sources live in the
/// sibling `app/` package; `directories` below is generated by
/// widgetbook_generator from the `@widgetbook.UseCase` annotations there.
class WidgetbookApp extends StatelessWidget {
  const WidgetbookApp({super.key});

  @override
  Widget build(BuildContext context) {
    return Widgetbook.material(
      directories: directories,
      addons: [
        MaterialThemeAddon(
          themes: [
            WidgetbookTheme(name: 'Design System', data: buildAppTheme()),
          ],
        ),
        DeviceFrameAddon(
          devices: [
            Devices.ios.iPhone13,
            Devices.android.samsungGalaxyS20,
            Devices.macOS.macBookPro,
          ],
        ),
        AlignmentAddon(),
      ],
    );
  }
}
